export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "shivam",
			profileImg: "/avatars/boy1.png",
			fullName: "Shivam_Menpara",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "priya",
					profileImg: "/avatars/girl1.jpg",
					fullName: "Priya_Sorthiya",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "raj",
			profileImg: "/avatars/boy2.png",
			fullName: "Raj_Zadafiya",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "vrutanshi",
					profileImg: "/avatars/girl2.jpg",
					fullName: "Vrutanshi_Rudani",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "mitansh",
			profileImg: "/avatars/boy2.png",
			fullName: "Mitansh_Rudani",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "dwij",
			profileImg: "/avatars/boy2.png",
			fullName: "Dwij_Rudani",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "mitanshi",
					profileImg: "/avatars/girl3.jpg",
					fullName: "Mitanshi_Rudani",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "Raj",
		username: "Raj_Radafiya",
		profileImg: "avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "Mitanshi",
		username: "Mitanshi_Rudani",
		profileImg: "avatars/girl1.jpg",
	},
	{
		_id: "3",
		fullName: "Shivam",
		username: "Shivam_Menpara",
		profileImg: "avatars/boy3.jpg",
	},
	{
		_id: "4",
		fullName: "Riya",
		username: "Riya_Rudani",
		profileImg: "avatars/girl2.jpg",
        
	},
];